# Generated by Django 6.0.4 on 2026-04-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(help_text="e.g., 'Frontend Developer Resume'", max_length=200),
        ),
    ]
