# Generated by Django 6.0.4 on 2026-05-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_last_status_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this job on homepage featured section'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in Nigerian Naira (₦)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in Nigerian Naira (₦)', max_digits=12, null=True),
        ),
    ]
